name: rastermap
channels:
  - conda-forge
dependencies:
  - python<3.10
  - pip
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - scikit-learn
  - pyqt<=5.11.3
  - pyqtgraph
  - h5py<3
  - natsort
  - pip:
    - scanimage-tiff-reader
