name: rastermap
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - ipython
  - ipykernel
  - pip
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - pandas
  - pytables
  - scikit-learn
  - pyqt<=5.11.3
  - pyqtgraph
  - natsort
  - tifffile
  - pip:
    - scanimage-tiff-reader
    - rastermap>0.1.0
