name: rastermap
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - numba
  - matplotlib
  - scipy
  - scikit-learn
  - pyqt
  - opencv
  - ipykernel
  - ipython
  - pandas
  - pytables
  - pyqtgraph
  - natsort
  - pip:
    - scanimage-tiff-reader
    - rastermap
